/* This file is generated by scripts/sync-furniture-assets.mjs. */
import type { FurnitureSourceModelFactory, FurnitureSourceModelLoader } from "../package-types";

export const FURNITURE_SOURCE_MODEL_LOADERS: Record<string, FurnitureSourceModelLoader> = {
  "crown-chest": () => import("../user-generated/crown-chest/model").then((module) => ({ createSourceModel: module.createSourceModel as FurnitureSourceModelFactory })),
};
