/* This file is generated by scripts/sync-furniture-assets.mjs. */
import type { FurnitureRuntimeFactory, FurnitureRuntimeLoader } from "../runtime-types";

export const FURNITURE_PACKAGE_RUNTIME_LOADERS: Record<string, FurnitureRuntimeLoader> = {
  "bay-cabinet": () => import("../builtin/bay-cabinet/runtime").then((module) => ({ createFurnitureModel: module.createFurnitureModel as FurnitureRuntimeFactory })),
  "desk": () => import("../builtin/desk/runtime").then((module) => ({ createFurnitureModel: module.createFurnitureModel as FurnitureRuntimeFactory })),
  "desk-chair": () => import("../builtin/desk-chair/runtime").then((module) => ({ createFurnitureModel: module.createFurnitureModel as FurnitureRuntimeFactory })),
  "double-bed": () => import("../builtin/double-bed/runtime").then((module) => ({ createFurnitureModel: module.createFurnitureModel as FurnitureRuntimeFactory })),
  "entry-cabinet": () => import("../builtin/entry-cabinet/runtime").then((module) => ({ createFurnitureModel: module.createFurnitureModel as FurnitureRuntimeFactory })),
  "lounge-chair": () => import("../builtin/lounge-chair/runtime").then((module) => ({ createFurnitureModel: module.createFurnitureModel as FurnitureRuntimeFactory })),
  "nightstand": () => import("../builtin/nightstand/runtime").then((module) => ({ createFurnitureModel: module.createFurnitureModel as FurnitureRuntimeFactory })),
  "queen-bed": () => import("../builtin/queen-bed/runtime").then((module) => ({ createFurnitureModel: module.createFurnitureModel as FurnitureRuntimeFactory })),
  "single-bed": () => import("../builtin/single-bed/runtime").then((module) => ({ createFurnitureModel: module.createFurnitureModel as FurnitureRuntimeFactory })),
  "sliding-wardrobe": () => import("../builtin/sliding-wardrobe/runtime").then((module) => ({ createFurnitureModel: module.createFurnitureModel as FurnitureRuntimeFactory })),
  "sofa-bed": () => import("../builtin/sofa-bed/runtime").then((module) => ({ createFurnitureModel: module.createFurnitureModel as FurnitureRuntimeFactory })),
  "stool": () => import("../builtin/stool/runtime").then((module) => ({ createFurnitureModel: module.createFurnitureModel as FurnitureRuntimeFactory })),
  "vanity": () => import("../builtin/vanity/runtime").then((module) => ({ createFurnitureModel: module.createFurnitureModel as FurnitureRuntimeFactory })),
  "wardrobe": () => import("../builtin/wardrobe/runtime").then((module) => ({ createFurnitureModel: module.createFurnitureModel as FurnitureRuntimeFactory })),
  "crown-chest": () => import("../user-generated/crown-chest/runtime").then((module) => ({ createFurnitureModel: module.createFurnitureModel as FurnitureRuntimeFactory })),
};
