/* This file is generated by scripts/sync-furniture-assets.mjs. */
import manifest0 from "../builtin/bay-cabinet/asset.json";
import manifest1 from "../builtin/desk/asset.json";
import manifest2 from "../builtin/desk-chair/asset.json";
import manifest3 from "../builtin/double-bed/asset.json";
import manifest4 from "../builtin/entry-cabinet/asset.json";
import manifest5 from "../builtin/lounge-chair/asset.json";
import manifest6 from "../builtin/nightstand/asset.json";
import manifest7 from "../builtin/queen-bed/asset.json";
import manifest8 from "../builtin/single-bed/asset.json";
import manifest9 from "../builtin/sliding-wardrobe/asset.json";
import manifest10 from "../builtin/sofa-bed/asset.json";
import manifest11 from "../builtin/stool/asset.json";
import manifest12 from "../builtin/vanity/asset.json";
import manifest13 from "../builtin/wardrobe/asset.json";
import manifest14 from "../user-generated/crown-chest/asset.json";
import type { FurnitureAssetCatalogEntry } from "../package-types";
import type { FurnitureAssetManifestV3 } from "../manifest-types";

export const FURNITURE_PACKAGE_CATALOG: FurnitureAssetCatalogEntry[] = [
  { manifest: manifest0 as FurnitureAssetManifestV3, contractHash: "a7c0ee73d890b69aee19b2abe14486b64cc1b4514b83f5d934bd89b5977fc451" },
  { manifest: manifest1 as FurnitureAssetManifestV3, contractHash: "b02ca89ddd5011a7947e0a06fdd2302de2030d2da1122170a2405fb2d519ca25" },
  { manifest: manifest2 as FurnitureAssetManifestV3, contractHash: "46dc75d24582beebaa9ab85082b4d9b605f91c9dbd02825b789792d516566cfb" },
  { manifest: manifest3 as FurnitureAssetManifestV3, contractHash: "b1b5cb6e7ca0611fe8a6bcc0d8b50b42ecf9d13fb5a1e8ab6aea06cae17bb23b" },
  { manifest: manifest4 as FurnitureAssetManifestV3, contractHash: "58f692a6aef3c36af5f927746d73d820e027066fc0245c00183b2bd6de1b2170" },
  { manifest: manifest5 as FurnitureAssetManifestV3, contractHash: "58d7fbaba4ab1dc00d92f18a0a18bd27129b2eeacfd493c8bafebac85cc556c3" },
  { manifest: manifest6 as FurnitureAssetManifestV3, contractHash: "fc8781f5337290340ff130ae01a36b146f006ef3e0412fc3299bc564318c9055" },
  { manifest: manifest7 as FurnitureAssetManifestV3, contractHash: "e89c050b75af160d33881aa22f91c1689bf42b5aed8dea3f7397371f67c84ca2" },
  { manifest: manifest8 as FurnitureAssetManifestV3, contractHash: "5dc027fefb60d84b032f0768f17c0d0799a4e5f5f66a7e7dc71864b557673f22" },
  { manifest: manifest9 as FurnitureAssetManifestV3, contractHash: "001901a8488394407dcac65104f48c8b22ef6c2cd42a4a27b3c7a0fa753f4aaa" },
  { manifest: manifest10 as FurnitureAssetManifestV3, contractHash: "e153c6359b5c0074f8dbee8c9d443e400bf838b2ecbd9115c0d7ccd594797b24" },
  { manifest: manifest11 as FurnitureAssetManifestV3, contractHash: "d005c428785046cf28c75a637fb5b81c885132b8c852ca5ed1af1d21851ba07a" },
  { manifest: manifest12 as FurnitureAssetManifestV3, contractHash: "7e149239915ef0f4aed7e4a55b3e9725df96a1244a2ed4241a5ff5c77a853f3d" },
  { manifest: manifest13 as FurnitureAssetManifestV3, contractHash: "cc11c3c6a0a6422154e171a7eaff7334d4d24e00b6f7a19948a947f593ace4e5" },
  { manifest: manifest14 as FurnitureAssetManifestV3, contractHash: "690c85ad0a16cfdb66d8b86c118204f277fd20fa87f5ca5518d049abfba8b415" },
];

export const BUILTIN_PACKAGE_CATALOG = FURNITURE_PACKAGE_CATALOG.filter((entry) => entry.manifest.assetScope === "builtin");
export const USER_GENERATED_PACKAGE_CATALOG = FURNITURE_PACKAGE_CATALOG.filter((entry) => entry.manifest.assetScope === "user-generated");
