/* This file is generated by scripts/sync-furniture-assets.mjs. */
import manifest0 from "../builtin/bay-cabinet/asset.json";
import manifest1 from "../builtin/desk/asset.json";
import manifest2 from "../builtin/desk-chair/asset.json";
import manifest3 from "../builtin/double-bed/asset.json";
import manifest4 from "../builtin/entry-cabinet/asset.json";
import manifest5 from "../builtin/lounge-chair/asset.json";
import manifest6 from "../builtin/nightstand/asset.json";
import manifest7 from "../builtin/queen-bed/asset.json";
import manifest8 from "../builtin/single-bed/asset.json";
import manifest9 from "../builtin/sliding-wardrobe/asset.json";
import manifest10 from "../builtin/sofa-bed/asset.json";
import manifest11 from "../builtin/stool/asset.json";
import manifest12 from "../builtin/vanity/asset.json";
import manifest13 from "../builtin/wardrobe/asset.json";
import manifest14 from "../user-generated/crown-chest/asset.json";
import type { FurnitureAssetCatalogEntry } from "../package-types";
import type { FurnitureAssetManifestV3 } from "../manifest-types";

export const FURNITURE_PACKAGE_CATALOG: FurnitureAssetCatalogEntry[] = [
  { manifest: manifest0 as FurnitureAssetManifestV3, contractHash: "a46f25440a9ddd6a27257fd6634d4bd38f4a5ac25aff80cf348e939651c72238" },
  { manifest: manifest1 as FurnitureAssetManifestV3, contractHash: "9aace6ee907ffa12bde98b15a1bf6c03fc698cc2bddba7b518c73365ab0d9eaa" },
  { manifest: manifest2 as FurnitureAssetManifestV3, contractHash: "75b6a948308036b3224a927a76bbbc6dadd492e0ed0c9b57b5f7ea169dd3a521" },
  { manifest: manifest3 as FurnitureAssetManifestV3, contractHash: "0155e2c576d193a0ebda3c8998cefdfe255ce1d4f2f439f43f000aaff87a88c1" },
  { manifest: manifest4 as FurnitureAssetManifestV3, contractHash: "6d4e4b5afbba17b7f373b5909ce23bcd019db8a1111c2e1513ea93aebde6201d" },
  { manifest: manifest5 as FurnitureAssetManifestV3, contractHash: "8a34459e573dc5580cb211b5e081bb45ab2bce2d30386316f68a7de5d61b011a" },
  { manifest: manifest6 as FurnitureAssetManifestV3, contractHash: "97cce4b0789a767ff27ef2e25eaaec657234f4ec3b75edab1648bc7aa2a17c14" },
  { manifest: manifest7 as FurnitureAssetManifestV3, contractHash: "1d2720c06db11d7738f08a60320375cf3c135b5259799714912e5f347427d901" },
  { manifest: manifest8 as FurnitureAssetManifestV3, contractHash: "51a212170f3d4e2ddd76b1ea9363f5787f01306355434b110c466daf5bc08d75" },
  { manifest: manifest9 as FurnitureAssetManifestV3, contractHash: "a3b542a61c19e9bcd8a4be7f5624c9180f81256703f04ceb4016f2ffac9b874c" },
  { manifest: manifest10 as FurnitureAssetManifestV3, contractHash: "ff30e9ec0dfbbf5d8bb56fdef127b9742c15e3ae8fd1eb039f884208e5209629" },
  { manifest: manifest11 as FurnitureAssetManifestV3, contractHash: "bfe8ed6f9485d867179f2269c10e104bbbe7123279d4149582353c7ac10f5d3d" },
  { manifest: manifest12 as FurnitureAssetManifestV3, contractHash: "054ed58a830f24f5d5422541f87f42de9635c493594481a4ba76018ef940de48" },
  { manifest: manifest13 as FurnitureAssetManifestV3, contractHash: "307110a822b9138b849753223402ade096d4994ed38644075a5b08a35ff70830" },
  { manifest: manifest14 as FurnitureAssetManifestV3, contractHash: "c58197f18aacbb1be35f092a8d300ae5e4a50dafcbd0d42ea5656017962584c9" },
];

export const BUILTIN_PACKAGE_CATALOG = FURNITURE_PACKAGE_CATALOG.filter((entry) => entry.manifest.assetScope === "builtin");
export const USER_GENERATED_PACKAGE_CATALOG = FURNITURE_PACKAGE_CATALOG.filter((entry) => entry.manifest.assetScope === "user-generated");
